---
name: default-bare

on:
  push:
  pull_request:
  schedule:  # run weekly, every Thursday 01:00
    - cron: '0 1 * * 4'

permissions: {}

jobs:
  build:
    permissions:
      contents: read
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      max-parallel: 4
      matrix:
        os: [ubuntu-24.04, ubuntu-22.04]
    env:
      ANSIBLE_CALLBACKS_ENABLED: profile_tasks
      ANSIBLE_EXTRA_VARS: ""
      ANSIBLE_ROLE: juju4.arkime
      SUITE: default

    steps:
      - uses: actions/checkout@v5
        with:
          path: ${{ env.ANSIBLE_ROLE }}
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.x'
      - name: ACL
        run: |
          sudo apt-get install -y acl || true
          mount
          sudo mount -o remount,acl / || true
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip3 install ansible-lint flake8 yamllint
          which ansible
          pip3 install ansible
          pip3 show ansible
          ls -l $HOME/.local/bin || true
          ansible --version
          cd $GITHUB_WORKSPACE/$ANSIBLE_ROLE
          [ -f molecule/${SUITE}/requirements.yml ] && ansible-galaxy install -r molecule/${SUITE}/requirements.yml
          { echo '[defaults]'; echo 'callbacks_enabled = profile_tasks, timer'; echo 'roles_path = ../:/home/runner/.ansible/roles'; echo 'ansible_python_interpreter: /usr/bin/python3'; } >> ansible.cfg
      - name: Environment
        run: |
          set -x
          pwd
          env
          find -ls
      - name: run test
        run: |
          cd $GITHUB_WORKSPACE/$ANSIBLE_ROLE && ansible-playbook -i localhost, --connection=local --become -vvv molecule/${SUITE}/converge.yml ${ANSIBLE_EXTRA_VARS}
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
      - name: idempotency run
        run: |
          cd $GITHUB_WORKSPACE/$ANSIBLE_ROLE && ansible-playbook -i localhost, --connection=local --become -vvv molecule/${SUITE}/converge.yml ${ANSIBLE_EXTRA_VARS} | tee /tmp/idempotency.log | grep -q 'changed=0.*failed=0'  && (echo 'Idempotence test: pass' && exit 0)  || (echo 'Idempotence test: fail' && cat /tmp/idempotency.log && exit 0)
      - name: On failure
        run: |
          systemctl -l --no-pager status
          systemctl -l --no-pager --failed
          ls -l /usr/bin/ | egrep '(python|pip|ansible)'
          pip freeze
          pip3 freeze
          ip addr
          cat /etc/resolv.conf
          host www.google.com
          ping -c 1 www.google.com || true
          ping -c 1 8.8.8.8 || true
        if: ${{ failure() }}
        continue-on-error: true
      - name: After script - ansible setup
        run: |
          ansible -i inventory --connection=local -m setup localhost
        if: ${{ always() }}
        continue-on-error: true
      - name: After script - systemd
        run: |
          systemctl -l --no-pager status arkimecapture || true
          systemctl -l --no-pager status arkimeviewer || true
          systemctl -l --no-pager status elasticsearch || true
          systemd-analyze --no-pager security arkimecapture || true
          systemd-analyze --no-pager security arkimeviewer || true
          systemd-analyze --no-pager security || true
          rsyslogd -v
          cat /etc/systemd/system/arkimecapture.service || true
          cat /etc/systemd/system/arkimeviewer.service || true
        if: ${{ always() }}
        continue-on-error: true
      - name: After script - network
        run: |
          ss -tunap
        if: ${{ always() }}
        continue-on-error: true
      - name: After script - arkime
        run: |
          set -x
          sudo cat /etc/elasticsearch/elasticsearch.yml || true
          sudo ls -la /opt/arkime/ || true
          sudo cat /opt/arkime/etc/config.ini || true
        if: ${{ always() }}
        continue-on-error: true
      - name: After script - logs
        run: |
          set -x
          sudo ls -laR /opt/arkime/logs || true
          sudo tail -200 /opt/arkime/logs/viewer.log || true
          sudo tail -200 /opt/arkime/logs/capture.log || true
          sudo tail -200 /var/log/elasticsearch/elasticsearch.log || true
        if: ${{ always() }}
        continue-on-error: true
      - name: After script - journalctl arkime capture
        run: |
          journalctl -xeu arkimecapture -l --no-pager
        if: ${{ always() }}
        continue-on-error: true
      - name: After script - journalctl arkime viewer
        run: |
          journalctl -xeu arkimeviewer -l --no-pager
        if: ${{ always() }}
        continue-on-error: true
      - name: After script - test run
        run: |
          set -x
          /opt/arkime/bin/arkime_config_interfaces.sh -c /opt/arkime/etc/config.ini -n default
          /opt/arkime/bin/capture -c /opt/arkime/etc/config.ini
        if: ${{ always() }}
        continue-on-error: true
